version: '3'

services:
  server:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/homework2
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php8.1-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/homework2
