version: '3.3'
services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/srv/app/public
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build: .
    restart: unless-stopped
    volumes:
      - .:/srv/app

volumes:
  caddy_data:
  caddy_config:
